---
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.WRITE_PACKAGE_TOKEN }}

      - name: Build and push image
        id: management_landing_page_build
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: ./
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/management-landing-page:${{ github.sha }}

      - name: Checkout the Gitops repository
        uses: actions/checkout@v4
        with:
          repository: fiaisis/gitops
          token: ${{ secrets.GITOPS_STAGING_EDIT_TOKEN }}

      - name: Edit the YAML management-landing-page file
        uses: mikefarah/yq@v4.44.2
        with:
          cmd: yq e -i '.spec.template.spec.containers[] |= select(.name == "management-landing-page").image = "ghcr.io/fiaisis/management-landing-page@${{ steps.plotting_service_build.outputs.digest }}"' './components/management-landing-page/management-landing-page.yml'

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "