---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      action-packages:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
          - "*"


  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      yarn-packages:
        patterns:
          - "*"